version: 1.0.{build}
skip_branch_with_pr: true
image:
  - Visual Studio 2017
  - ubuntu
install:
  - sh: sudo apt-get remove -f -y powershell
  - sh: sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev
  - sh: sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
  - git submodule update --init --recursive
build_script:
  - ps: .\ci_build.ps1
artifacts:
  - path: '**\*.nupkg'
